version: "2.1"
services:
  minecraft_bedrock:
    image: itzg/minecraft-server
    container_name: inethi-minecraft
    environment:
      - "EULA=TRUE"
      - "SERVER_NAME=inethi-java"
      #  "VERSION=1.18.0.02"
      #- SERVER_PORT
      #- SERVER_PORT_V6
      # - GAMEMODE
      # - DIFFICULTY
      # - LEVEL_TYPE
      # - ALLOW_CHEATS
      # - MAX_PLAYERS
      # - ONLINE_MODE
      # - WHITE_LIST
      # - VIEW_DISTANCE
      # - TICK_DISTANCE
      # - PLAYER_IDLE_TIMEOUT
      # - MAX_THREADS65565555qw
      # - LEVEL_NAME
      # - LEVEL_SEED
      # - DEFAULT_PLAYER_PERMISSION_LEVEL
      # - TEXTUREPACK_REQUIRED
      # - SERVER_AUTHORITATIVE_MOVEMENT
      # - PLAYER_MOVEMENT_SCORE_THRESHOLD
      # - PLAYER_MOVEMENT_DISTANCE_THRESHOLD
      # - PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS
      # - CORRECT_PLAYER_MOVEMENT

    tty: true
    stdin_open: true
    
    ports:
      - "25565:25565"
      - "25575:25575"

    volumes:
      - mc_data_java:/data

    restart: always


volumes:
  mc_data_java:
 

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"

