version: "2"

services:
  traefik:
    image: traefik:v1.7
    container_name: inethi-traefikssl
 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TRAEFIKSSL_VOLUME}/traefik.toml:/traefik.toml"
      - "${TRAEFIKSSL_VOLUME}/acme.json:/acme.json"
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_API_RULE}`)"
      - "traefik.http.routers.api.service=${TRAEFIK_API_SERVICE}"
      - "traefik.http.routers.api.entrypoints=${TRAEFIK_API_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
