[entryPoints.http]
  address = ":80"
  [entryPoints.http.http.redirections.entryPoint]
    to = "https"
    scheme = "https"

[entryPoints.https]
  address = ":443"
  [entryPoints.https.http.tls]
    certResolver = "main"

# Let's Encrypt
[certificatesResolvers.main.acme]
  email = "inethi4us@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.main.acme.dnsChallenge]
    provider = "route53"