version: '3'

services:
  inethi-user-management-api:
    container_name: inethi-user-management-api
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - inethi-user-management-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`${TRAEFIK_API_RULE_DJANGO}`)"
      - "traefik.http.routers.django.entrypoints=${TRAEFIK_ENTRYPOINT}"

    ports:
      - "8000:8000"

  inethi-user-management-mysql:
    container_name: inethi-user-management-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: 'inethi-user-management-api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - '${DJANGO_MNT}/mysql/db:/var/lib/mysql'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.djangomysql.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
