version: '3'

services:
  voucherapiprod:
    container_name: inethi-paymentprod-api
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: bash -c 'gunicorn --bind 0.0.0.0:80 manage:app --log-level debug'

    environment:
      - FLASK_APP=endpoints/__init__.py
      - FLASK_ENV=production
      - "DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@rdmariadb/${MYSQL_DB}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voucherapiprod.rule=Host(`${TRAEFIK_API_RULE_FLASK_PROD}.${inethiDN}`)"
      - "traefik.http.routers.voucherapiprod.entrypoints=${TRAEFIK_ENTRYPOINT}"

  voucherweb:
    image: nginx
    container_name: inethi-paymentprod-web
    restart: always
    volumes:
      - "${VOUCHER_VOLUME}/html:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voucher.rule=Host(`${TRAEFIK_API_RULE_VOUCHER}.${inethiDN}`)"
      - "traefik.http.routers.voucher.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
