version: "2.1"
services:
  minecraft_bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: inethi-minecraft_bedrock
    environment:
      - "EULA=TRUE"
      - "SERVER_NAME=inethi"
      - "VERSION=1.18.0.02"
      #- SERVER_PORT
      #- SERVER_PORT_V6
      # - GAMEMODE
      # - DIFFICULTY
      # - LEVEL_TYPE
      # - ALLOW_CHEATS
      # - MAX_PLAYERS
      # - ONLINE_MODE
      # - WHITE_LIST
      # - VIEW_DISTANCE
      # - TICK_DISTANCE
      # - PLAYER_IDLE_TIMEOUT
      # - MAX_THREADS
      # - LEVEL_NAME
      # - LEVEL_SEED
      # - DEFAULT_PLAYER_PERMISSION_LEVEL
      # - TEXTUREPACK_REQUIRED
      # - SERVER_AUTHORITATIVE_MOVEMENT
      # - PLAYER_MOVEMENT_SCORE_THRESHOLD
      # - PLAYER_MOVEMENT_DISTANCE_THRESHOLD
      # - PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS
      # - CORRECT_PLAYER_MOVEMENT
    
    ports:
      - "19132:19132/udp"

    volumes:
      - mc_data_bedrock:/data

    restart: always
    

volumes:
  mc_data_bedrock:
 

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"

