version: '3.3'
services:
    ludo:
      image: cybercitizen01/the-ludo-game
      container_name: inethi-ludo
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ludo.rule=Host(`${TRAEFIK_API_RULE_HOST}.${inethiDN}`)"
        - "traefik.http.routers.ludo.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
