version: '2'

services:
  keycloak-gatekeeper:
    image: hackinglab/keycloak-gatekeeper:latest
    container_name: inethi-traefik-keycloak-gatekeeper
    volumes:
      - "${GATEKEEPER_VOLUME}/keycloak-gatekeeper.conf:/etc/keycloak-gatekeeper.conf"
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak-gatekeeper.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloakgatekeeper.rule=Host(`${KEYCLOAK_GATEKEEPER_TRAEFIK_API_RULE}`)"
      - "traefik.http.routers.keycloakgatekeeper.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: ${INETHI_NETWORK}
