version: '3'

services:
  mysql:
      image: mysql:5.7
    
      container_name: inethi-mysql-keycloak
      restart: always
      environment:
        - "MYSQL_ROOT_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}"
        - "MYSQL_DATABASE=keycloak"
        - "MYSQL_USER=${KEYCLOAK_ADMIN_USER}"
        - "MYSQL_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}"
      volumes:
        - "${MYSQLDB_VOLUME}:/var/lib/mysql"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mysql-keycloak.rule=Host(`${MYSQL_KEYCLOAK_TRAEFIK_API_RULE}`)"
        - "traefik.http.routers.mysql-keycloak.entrypoints=${TRAEFIK_ENTRYPOINT}"

  keycloak:
      image: jboss/keycloak
   
      container_name: inethi-keycloak
      environment:
        - "HOSTNAME=${KEYCLOAK_TRAEFIK_API_RULE}"
        - "KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}" 
        - "KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}"
        - "KEYCLOAK_USER=${KEYCLOAK_USER}" 
        - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
        - "DB_VENDOR=MYSQL"
        - "DB_ADDR=inethi-mysql-keycloak"
        - "DB_DATABASE=keycloak"
        - "DB_USER=${KEYCLOAK_ADMIN_USER}"
        - "DB_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}"
        - "PROXY_ADDRESS_FORWARDING=true"
       
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      #ports:
       #  - 20061:8080
      
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_TRAEFIK_API_RULE}`)"
      - "traefik.http.routers.keycloak.entrypoints=${TRAEFIK_ENTRYPOINT}"
      #- "traefik.http.routers.keycloak.tls.certresolver=sslresolver"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      

# network for inethi
networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
