version: '3'

services:
  mysql:
    image: mysql
    container_name: inethi-nextcloud-mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - "${MYSQL_VOLUME}:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=inethi_nextcloud"
      - "MYSQL_USER=inethi"
   

  nextcloud:
    image: nextcloud
    container_name: inethi-nextcloud
    restart: unless-stopped
    links:
      - mysql 
    volumes:
      - "${NEXTCLOUD_VOLUME}:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${TRAEFIK_API_RULE_NEXTCLOUD}.${inethiDN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"