version: '3.3'
services:
  scratch-gui:
    container_name: inethi-scratch
    image: leejoneshane/scratch3
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scratch.rule=Host(`${TRAEFIK_API_RULE_HOST}.${inethiDN}`)"
      - "traefik.http.routers.scratch.entrypoints=${TRAEFIK_ENTRYPOINT}"

networks:
  default:
    external:
      name: inethi-bridge-traefik
