version: '3'

services:
  
  nginx:
      image: nginx
      container_name: inethi-nginx
      restart: always
      networks:
        default:
          ipv4_address: "${NGINX_IPV4}"
      volumes:
        - '${NGINX_VOLUME}/html:/usr/share/nginx/html'
        - '${NGINX_VOLUME}/etc:/etc/nginx'
      
networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
