version: '3'
services:

  wordpress:
    image: wordpress:latest
    container_name: inethi-wordpress
    volumes:
      - "${WORDPRESS_MOUNT}:/var/www/html"
    env_file: "./secrets/secret_passwords.env"
    environment:
      - "WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}"
      - "WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}"
      - "WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}"
      - "WORDPRESS_DB_USER=${WORDPRESS_DB_USER}"
      - "WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}"
    depends_on:
      - mariadb
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${TRAEFIK_API_RULE_WORDPRESS}.${inethiDN}`)"
      - "traefik.http.routers.wordpress.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"

  mariadb:
    image: mariadb:latest
    container_name: inethi-mariadb
    volumes:
      - "${MARIADB_MOUNT}:/var/lib/mysql"
    env_file: "./secrets/secret_passwords.env"
    environment:
      - "MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}"
      - "MYSQL_USER=${WORDPRESS_DB_USER}"
      - "MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}"
      - "MYSQL_DATABASE=${WORDPRESS_DB_NAME}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mariadb.rule=Host(`${TRAEFIK_API_RULE_MARIADB}.${inethiDN}`)"
      - "traefik.http.routers.mariadb.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.mariadb.tls.certresolver=letsencrypt"

  adminer:
    image: adminer
    container_name: inethi-adminer
    restart: always
    links:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${TRAEFIK_API_RULE_ADMINER}.${inethiDN}`)"
      - "traefik.http.routers.adminer.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"