version: '3'

services:

  openvpn:
    image: kylemanna/openvpn
    container_name: inethi-openvpn

    cap_add:
     - NET_ADMIN
   
    volumes:
      - "${OPENVPN_VOLUME}:/etc/openvpn"
      
    ports:
      - 1194:1194/udp


      

# network for inethi
networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
