version: '3'
services:
  
  web:
    container_name: inethi-radiusdesk-nginx
    
    build:
      context: ./
      dockerfile: Dockerfile-nginx

    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radiusdesk.rule=Host(`${TRAEFIK_API_RULE_HOST}.${inethiDN}`)"
        - "traefik.http.routers.radiusdesk.entrypoints=${TRAEFIK_ENTRYPOINT}"
      

  php:
    image: php:7-fpm

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"


    


  
 
