version: '3'

services:
  nginx:
    image: nginx
    container_name: inethi-traefik-nginx
    restart: always
    volumes:
        - "${NGINX_VOLUME}/html:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.splash.rule=${TRAEFIK_RULE}"
      - "traefik.http.routers.splash.entrypoints=${TRAEFIK_ENTRYPOINT}"
    networks:
      - "${INETHI_NETWORK}"

networks:
    web:
        external: true
